
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 10;
  public static final int DIVIDE = 30;
  public static final int INTEGERLIT = 51;
  public static final int AMPERSOR = 38;
  public static final int GE = 34;
  public static final int STRINGLIT = 53;
  public static final int INTEGER = 20;
  public static final int LPAREN = 41;
  public static final int MINUS = 28;
  public static final int TILDE = 40;
  public static final int RPAREN = 42;
  public static final int EXCLAIM = 39;
  public static final int STATIC = 5;
  public static final int SEMICOLON = 47;
  public static final int LT = 31;
  public static final int RIGHTSQ = 46;
  public static final int COMMA = 48;
  public static final int CLASS = 2;
  public static final int LEFTSQ = 45;
  public static final int PLUS = 27;
  public static final int ASSIGN = 26;
  public static final int MAIN = 3;
  public static final int IF = 11;
  public static final int AMPERSAND = 37;
  public static final int THIS = 25;
  public static final int DOT = 49;
  public static final int LE = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int RETURN = 8;
  public static final int TRUE = 16;
  public static final int RIGHTCURLY = 44;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int VOID = 6;
  public static final int FLOATLIT = 52;
  public static final int EQ = 35;
  public static final int LEFTCURLY = 43;
  public static final int TIMES = 29;
  public static final int ELSE = 13;
  public static final int WHILE = 14;
  public static final int FLOAT = 21;
  public static final int PUBLIC = 4;
  public static final int THEN = 12;
  public static final int NE = 36;
  public static final int EXTENDS = 7;
  public static final int STRING = 19;
  public static final int FALSE = 17;
  public static final int GT = 33;
  public static final int NULLLIT = 18;
  public static final int PRINT = 23;
  public static final int LENGTH = 24;
  public static final int DO = 15;
  public static final int IDENTIFIER = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "MAIN",
  "PUBLIC",
  "STATIC",
  "VOID",
  "EXTENDS",
  "RETURN",
  "NEW",
  "DISPLAY",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "TRUE",
  "FALSE",
  "NULLLIT",
  "STRING",
  "INTEGER",
  "FLOAT",
  "BOOLEAN",
  "PRINT",
  "LENGTH",
  "THIS",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LT",
  "LE",
  "GT",
  "GE",
  "EQ",
  "NE",
  "AMPERSAND",
  "AMPERSOR",
  "EXCLAIM",
  "TILDE",
  "LPAREN",
  "RPAREN",
  "LEFTCURLY",
  "RIGHTCURLY",
  "LEFTSQ",
  "RIGHTSQ",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "IDENTIFIER",
  "INTEGERLIT",
  "FLOATLIT",
  "STRINGLIT",
  "PRIVATE",
  "SUPER",
  "INS",
  "BITAND",
  "BITOR",
  "BITXOR",
  "MOD"
  };
}

